#!/usr/bin/python

import sys
sys.path.append('../common')

import os
import time
import logging
import argparse
import shutil
from util import check_output, check_both, run_bg, strip_comments

# click
CLICK_CONF = 'autogen.click'
CLICK = '/usr/local/bin/click'

# tc
TC_SETUP = './tc_setup.py'

# apache
APACHE = '/etc/init.d/apache2'
APACHE_PORTS = '/etc/apache2/ports.conf'
APACHE_PORTS_BAK = '%s.backup' % APACHE_PORTS
APACHE_DEFAULT_SITE = '/etc/apache2/sites-available/default'
APACHE_SITES_AVAILABLE = '/etc/apache2/sites-available'
APACHE_SITES_ENABLED = '/etc/apache2/sites-enabled'


# Prepare apache VirtualHost for each server ip in servers_file
def configure_apache(servers_file):
    try:
        # back up the existing ports.conf
        shutil.copyfile(APACHE_PORTS, APACHE_PORTS_BAK)
            
        with open(servers_file, 'r') as serversfile:
            for line in strip_comments(serversfile):
                ip = line.strip()

                # append virtual hosts to ports.conf
                with open(APACHE_PORTS, 'a') as portsfile:
                        portsfile.write('\n\nNameVirtualHost %s:8080\n' % ip)
                        portsfile.write('Listen %s:8080' % ip)
                portsfile.closed

                # make a conf file for this virtual host
                confpath = os.path.join(APACHE_SITES_AVAILABLE, ip)
                with open(APACHE_DEFAULT_SITE, 'r') as defaultfile:
                    with open(confpath, 'w') as conffile:
                        for line in defaultfile:
                            if '<VirtualHost' in line:
                                conffile.write('<VirtualHost %s:8080>\n' % ip)
                            else:
                                conffile.write(line)
                    conffile.closed
                defaultfile.closed

                # symlink conf file to sites-enabled
                linkpath = os.path.join(APACHE_SITES_ENABLED, ip)
                if not os.path.islink(linkpath):
                    os.symlink(confpath, linkpath)
        
        
        serversfile.closed



    except Exception as e:
        logging.getLogger(__name__).error(e)

# Put apache back to normal
def reset_apache(servers_file):
    try:
        # restore ports.conf from backup
        if os.path.isfile(APACHE_PORTS_BAK):
            shutil.move(APACHE_PORTS_BAK, APACHE_PORTS)
        else:
            logging.getLogger(__name__).warning('Could not find %s' % APACHE_PORTS_BAK)

        # remove conf files
        with open(servers_file, 'r') as serversfile:
            for line in strip_comments(serversfile):
                ip = line.strip()

                confpath = os.path.join(APACHE_SITES_AVAILABLE, ip)
                if os.path.isfile(confpath):
                    os.remove(confpath)

                linkpath = os.path.join(APACHE_SITES_ENABLED, ip)
                if os.path.islink(linkpath):
                    os.remove(linkpath)
        serversfile.closed

    except Exception as e:
        logging.getLogger(__name__).error(e)

def get_topo_file(suffix):
    if args.topology[-1] == '/':
        args.topology = args.topology[0:-1]
    topo_name = os.path.basename(args.topology)
    filepath = os.path.join(args.topology, '%s.%s' % (topo_name, suffix))
    if not os.path.isfile(filepath):
        logging.getLogger(__name__).error('Could not find %s' % filepath)
        exit(-1)
    return filepath

def autogen_click_conf(servers_file, clients_file):
    logging.getLogger(__name__).debug('Autogenerating %s from %s and %s'\
        % (CLICK_CONF, servers_file, clients_file))
    with open(CLICK_CONF, 'w') as clickfile:
        clickfile.write('// This file is autogenerated. Do not hand edit.\n\n')
        with open(servers_file, 'r') as serversfile:
            for line in strip_comments(serversfile):
                clickfile.write('KernelTun(%s/8) -> Discard;\n' % (line.strip()))
        serversfile.closed
        with open(clients_file, 'r') as clientsfile:
            for line in strip_comments(clientsfile):
                clickfile.write('KernelTun(%s/8) -> Discard;\n' % (line.strip()))
        clientsfile.closed
    clickfile.closed

def install_filters(links_file):
    with open(links_file, 'r') as linksf:
        for line in strip_comments(linksf):
            elems = line.split(' ')
            check_output('%s update %s %s -c %i'\
                % (TC_SETUP, elems[0], elems[2], int(elems[1].split('link')[1])))
    linksf.closed

def execute_event(event):
    logging.getLogger(__name__).info('Updating link:  %s' % ' '.join(event))
    try:
        check_output('%s update -c %i -b %s -l %s'\
            % (TC_SETUP, int(event[1].split('link')[1]), event[2], event[3]))
    except Exception as e:
        logging.getLogger(__name__).error(e)

def run_events():
    events = []
    with open(get_topo_file('events'), 'r') as eventsf:
        for line in strip_comments(eventsf):
            events.append(line.split(' '))
    eventsf.closed

    logging.getLogger(__name__).info('Running link events...')
    for event in events:
        # decide when to execute this event
        if event[0] is '*':
            raw_input('Press enter to run event:  %s' % ' '.join(event))
        else:
            try:
                time.sleep(float(event[0]))
            except:
                logging.getLogger(__name__).warning('Skipping invalid event: %s' % ' '.join(event))
                continue
        execute_event(event)
    logging.getLogger(__name__).info('Done running events.')

def start_network():
    logging.getLogger(__name__).info('Starting simulated network...')

    # Create fake NICs
    logging.getLogger(__name__).info('Creating network interfaces...')
    autogen_click_conf(get_topo_file('servers'), get_topo_file('clients'))
    run_bg('%s %s' % (CLICK, CLICK_CONF))

    # Set up traffic shaping
    logging.getLogger(__name__).info('Enabling traffic shaping...')
    check_output('%s start' % TC_SETUP)
    install_filters(get_topo_file('bottlenecks'))

    # Launch apache instances
    logging.getLogger(__name__).info('Configuring apache...')
    configure_apache(get_topo_file('servers'))
    check_output('%s restart' % APACHE, shouldPrint=False)

    logging.getLogger(__name__).info('Network started.')

def stop_network():
    logging.getLogger(__name__).info('Stopping simulated network...')

    # stop apache instances
    logging.getLogger(__name__).info('Stopping apache...')
    reset_apache(get_topo_file('servers'))
    check_output('%s restart' % APACHE, shouldPrint=False)

    # Stop traffic shaping
    logging.getLogger(__name__).info('Disabling traffic shaping...')
    try:
        check_output('%s stop' % TC_SETUP)
    except Exception as e:
        logging.getLogger(__name__).error(e)

    # Destroy fake NICs
    logging.getLogger(__name__).info('Destroying network interfaces...')
    try:
        check_both('killall -9 click', shouldPrint=False)
        time.sleep(0.1)
    except:
        pass
    logging.getLogger(__name__).info('Network stopped.')


def main():

    if args.command == 'start':
        start_network()
    elif args.command == 'run':
        run_events()
    elif args.command == 'stop':
        stop_network()
    elif args.command == 'restart':
        stop_network()
        start_network()

if __name__ == "__main__":
    # set up command line args
    parser = argparse.ArgumentParser(description='Launch a simulated network.')
    parser.add_argument('topology', help='directory containing the topology files (topo.clients, topo.servers, topo.bottlenecks, topo.events, where topo is the name of the topology)')
    parser.add_argument('command', choices=['start','stop','restart','run'], help='start/stop/restart the network, or run a series of link events?')
    parser.add_argument('-q', '--quiet', action='store_true', default=False, help='only print errors')
    parser.add_argument('-v', '--verbose', action='store_true', default=False, help='print debug info. --quiet wins if both are present')
    args = parser.parse_args()
    
    # set up logging
    if args.quiet:
        level = logging.WARNING
    elif args.verbose:
        level = logging.DEBUG
    else:
        level = logging.INFO
    logging.basicConfig(
        format = "%(levelname) -10s %(asctime)s %(module)s:%(lineno) -7s %(message)s",
        level = level
    )

    main()
